wip

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -1,5 +1,6 @@
 ---
 on:
+  workflow_dispatch:
   push:
     branches:
       - master
@@ -49,6 +50,9 @@ jobs:
               fi
           - name: Check URLs
             run: |
+              echo "failed_url=https://www.devtal.de/api/" >> $GITHUB_ENV
+              exit 1
+              
               for url in $urls; do
                 echo "Checking $url"
                 isValid=$(curl \
@@ -71,7 +75,7 @@ jobs:
             with:
               script: |
                   github.issues.createComment({
-                    issue_number: context.issue.number,
+                    issue_number: 3,
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     body: 'The URL check failed. Please check [the validator output](https://validator.spaceapi.io/ui/?url=$failed_url).
